### ISSUE TITLE
Issue running script...

### ISSUE THREAD

**Issue by theharshl** [Flobul/optoma#1]
Found this script and was hoping to use it for a particular command that I can't seem to run over PJLink specifically, the resync command.

Sorry if I am using the script incorrectly, but I get an error when I try the following command:
./optoma.sh Power Status 10.20.30.56 4352
./optoma.sh: line 83: syntax error in conditional expression: unexpected token `('
./optoma.sh: line 83: syntax error near `+(['
./optoma.sh: line 83: `		Ok) if [[ ${RES:24:4} = +([0-9][0-9][0-9][0-9]) ]]'

Is it currently broken, or am I doing something wrong? Sorry, I don't have the knowledge to fix it myself. :(

**Comment by Flobul** [comment]
Hello.
Port 4352 is espacially used for PJLink protocol.
This script is based on telnet protocol (default port: 23).

Commands are very different.

You should try the PJLink script by DaveTHw or be sure telnet is open on your beamer and change it in the command line when using this script.

Nevertheless I will look into this error line.

**Comment by theharshl** [comment]
> Hello.
> Port 4352 is espacially used for PJLink protocol.
> This script is based on telnet protocol (default port: 23).

Right, I actually tried both. The projector is listening on 23, but when I access it directly it seems to close it almost instantly. Perhaps it is expecting a command with the connection immediately rather than an interactive session.

I am using PJLink for power commands currently, but the re-sync command doesn't appear to be available over that protocol, likely because it is not a standard command for all manufacturers.

I will keep an eye out for an update on the error.

Thanks for your work on this! Sure do appreciate it!

**Comment by Flobul** [comment]
If it close it instantly, the beamer is not listening on this port.
So this script can't work.
Make sure port 23 is really the telnet port for your beamer, and that it is really open. (command "nmap" in bash.

PJLink stantard does only have a few basic commands.
(check specifications : https://pjlink.jbmia.or.jp/english/data/5-1_PJLink_eng_20131210.pdf)
Maybe you can control re-sync over http.
Optoma last beamers use a cgi based controller over http (http://@IP/form/control_cgi?btn_powon=Power%20On...) to get informations and send commands. You can't either acces via the web page with control page or this link.

**Comment by Flobul** [comment]
I just edited the script for your expression error.
But the real problem is your telnet port on your beamer.

**Comment by theharshl** [comment]
Thanks for updating it. I was able to get everything working. Appreciate
your work on this, really helpful!
